[package]
name = "librtbit-buffers"
version = "0.1.0"
edition = "2024"
description = "Utils to work with byte buffers in librtbit source code"
license = "MIT"
repository = "http://100.92.54.45:3002/indexarr/librtbit-buffers"

[dependencies]
serde = "1"
serde_derive = "1"
clone_to_owned = { git = "http://100.92.54.45:3002/indexarr/librtbit-clone-to-owned.git", tag = "v0.1.0", package = "librtbit-clone-to-owned" }
bytes = "1"

[lints.clippy]
all = { level = "warn", priority = -1 }

[lints.rust]
unused = "warn"
